### PR TITLE
Added links to run notebooks in SageMaker Studio Lab

### PR DESCRIPTION
**Pull request by 1inuxoid**
As Amazon kindly provides generous Jupyter notebooks environment on [SageMaker Studio Lab](https://studiolab.sagemaker.aws/) I thought it would be nice to be able to run pytudes there.

### CODE REVIEW

**Comment by norvig** [comment]
I suppose it is reasonable to add SageMaker. I don't know much about it. But the change should be in py/pytudes.py which is used to generate README.md .

**Comment by 1inuxoid** [comment]
Apologies, I should have studied the repository better. I will update the pull-request with changes to `py/pytudes.py`.

**Comment by 1inuxoid** [comment]
I regenerated README.md using the updated code, I hope the change is more meaningful now.

**Comment by norvig** [comment]
Very nice, thank you!

**Pull request merged**
