### PR TITLE
Input now downloads files from Github

### PR DESCRIPTION
**Pull request by rmeertens**
Previously interested programmers who only downloaded the iPython notebook had to download your specific input data separately (or download their own inputs). With this fix the input files are downloaded from your Github repository as soon as Input(day) is called.

### CODE REVIEW

**Comment by polyzen** [comment]
The commit also changes(lowers) the version number.

**Comment by rmeertens** [comment]
Welp, let's not do that...

**Comment by norvig** [comment]
I thought of doing something like this, and yours is a good implementation. The question is whether this is the right thing:
* Is it worth complicating `Input`?
* Should we try to get the user's own input files, not mine?
* Should there be a separate command to download files?
* Or should `Inout` just fetch the input without caching it in the filesystem?
* Or should I do a `! wget` or `! curl`  in Notebook cells?

**Comment by polyzen** [comment]
It should use local input data if available. If that's not found, perhaps prompt to download upstream's(your's) or exit.

**Comment by rmeertens** [comment]
My opinion on mentioned points:
- Is it worth complicating Input? -> The biggest problem I see with the Input function I made is that it actually does two things (load input AND download data if it does not exist...), and it's not clear that it does it. We could create a `def Download(day)` function that downloads the input for a specific day. I would download the input from your Git repo... This way the assertions keep working for what was once you input, and Eric Wastl pays less for his servers...
- Should we try to get the user's own input files, not mine? -> My implementation only downloads your input files if no input file is present. Granted, this is not clear when running this code. 
- Should there be a separate command to download files? -> This is a great idea! We could even combine it with the last suggestion and wget all files at once at the top of te notebook. 
- Or should Inout just fetch the input without caching it in the filesystem? -> Wouldn't do that, as it will keep spamming git servers and add unnecessary delays when experimenting with the code. 
- Or should I do a ! wget or ! curl in Notebook cells? -> Yeah, that would work perfectly! Then the question is: do we download everything at the top of the notebook, or at the start of every day?

**Comment by norvig** [comment]
Sorry to be late responding -- I think the simplest solution is one `! wget` at the start to download all my files from github and store them locally. Some people have wget, some have curl, so something like this?

     ! [ -e input24.txt ] || curl -O ... || wget ...

**Pull request merged**
